server {
    listen 80;
    # listen 80 default_server;
    # listen 443 ssl default_server;
    # listen 443;
    # listen [::]:80 default_server;

    index       index.html
    root        /var/www/anfitriaolocal;
    server_name anfitriaolocal.com.br;

    location / {
        try_files $uri $uri/ =404;
    }
}
