# Global settings for nginx

user www-data; # The user and group that the worker processes will run as

worker_processes auto; # The number of worker processes to spawn. 'auto' will set it to the number of available CPU cores.

pid /run/nginx.pid; # The file where the process ID of the master process will be stored.

# The 'events' block is used to configure the event handling model for nginx. It contains settings that affect how nginx handles connections and events.
events {

    worker_connections 1024; # The maximum number of simultaneous connections that can be opened by a worker process.
    # This value can be increased based on the server's capacity and expected traffic.

    # multi_accept on;
}

# The 'http' block is used to configure the HTTP server settings for nginx. It contains settings that affect how nginx handles HTTP requests and responses.
http {

    ##
    # Basic Settings
    ##

    default_type application/octet-stream;

    include /etc/nginx/mime.types;

    keepalive_timeout 65; # The time (in seconds) that nginx will wait for a new request before closing the connection.

    sendfile on;

    tcp_nopush on;
    tcp_nodelay on;

    types_hash_max_size 2048;

    # server_tokens off;

    # server_names_hash_bucket_size 64;
    # server_name_in_redirect off;

    # server blocks (virtual hosts) go here
    include /etc/nginx/conf.d/*.conf;
    include /etc/nginx/sites-enabled/*;
}
