server {
    index        observatorio.marilia.local.html;
    listen       80;
    root         /var/www/observatorio.marilia.local;
    server_name  observatorio.marilia.local www.observatorio.marilia.local;
}

# listen 80 default_server;
# listen 443 ssl default_server;
# listen 443;
# listen [::]:80 default_server;

    # location / {
        # try_files $uri $uri/ =404;
    # }
