server {
    index  nginx.local.html;

    listen  80 default_server;
    listen  [::]:80 default_server;

    listen  443 ssl default_server;
    listen  [::]:443 ssl default_server;

    root  /var/www/nginx.local;

    server_name  nginx.local;

    ssl_certificate      /etc/nginx/certs/nginx.local/nginx.local.crt;
    ssl_certificate_key  /etc/nginx/certs/nginx.local/nginx.local.key;

    location / {
        # first attempt to serve request as file
        # if that fails, try serving it as a directory
        # if that fails, fall back to displaying a 404
        try_files $uri $uri/ =404;
    }

    location /images {
        autoindex on;
    }

    error_page 404 /404.html;

    location = /404.html {
        internal;
    }
    
    error_page 500 502 503 504 /50x.html;

    location = /50x.html {
        internal;
    }

    location /500 {
        fastcgi_pass unix:/this/will/fail;
    }
}
