server {
    index        nginx.local.html;
    listen       80;
    listen       443 ssl;
    root         /var/www/nginx.local;
    server_name  nginx.local;

    ssl_certificate      /etc/nginx/certs/nginx.local.crt;
    ssl_certificate_key  /etc/nginx/certs/nginx.local.key;
}

# listen 80 default_server;
# listen 443 ssl default_server;
# listen 443;
# listen [::]:80 default_server;

    # location / {
        # try_files $uri $uri/ =404;
    # }
